services:
  dcmweb:
    build:
      context: ./docker/dcmweb
      dockerfile: Dockerfile
    container_name: dcm-web
    # db起動後にwebを起動
    depends_on:
      - dcmdb
    # ローカルのhtmlをコンテナの/var/www/htmlにマウント
    volumes:
      - ./html:/var/www/html
    # ポートを割り当て
    ports:
      - ${WEB_PORT}:80
    command: >
      sh -c "
      cd /var/www/html &&
      rm -f config/app.php &&
      ln -s /var/www/html/config/app.local.php /var/www/html/config/app.php &&
      composer install --no-interaction &&
      /usr/sbin/httpd -D FOREGROUND
      "
    tty: true

  dcmdb:
    # mysql:5.5イメージから構築
    image: mysql:5.5
    container_name: dcm-db
    volumes:
      - dcmdb-data:/var/lib/mysql
      - ./docker/dcmdb/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/dcmdb/sql/cakephptest.sql:/docker-entrypoint-initdb.d/01_cakephptest.sql
      - ./docker/dcmdb/sql/masterkanri.sql:/docker-entrypoint-initdb.d/02_masterkanri.sql
    # .envで環境変数を管理
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    # ポートを割り当て
    ports:
      - ${DB_PORT}:3306
    command: >
      bash -c "chmod 644 /etc/mysql/conf.d/my.cnf && docker-entrypoint.sh mysqld"

volumes:
  dcmdb-data:
