services:
  dcmweb:
    build:
      context: ./docker/dcmweb
      dockerfile: Dockerfile
    container_name: dcm-web
    # db起動後にwebを起動
    depends_on:
      - dcmdb
      - spwebdb
    # ローカルのhtmlをコンテナの/var/www/htmlにマウント
    volumes:
      - ./html:/var/www/html
    ports:
      - ${WEB_PORT}:80
    command: >
      sh -c "
      cd /var/www/html &&
      rm -f config/app.php &&
      ln -s /var/www/html/config/local/app.php /var/www/html/config/app.php &&
      composer install --no-interaction &&
      /usr/sbin/httpd -D FOREGROUND
      "
    tty: true

  dcmfile:
    build:
      context: ./docker/dcmfile
      dockerfile: Dockerfile
    container_name: dcm-file
    ports:
      - "${FILE_PORT}:22"
    depends_on:
      - dcmweb

  dcmdb:
    build:
      context: ./docker/dcmdb
      dockerfile: Dockerfile
    container_name: dcm-db
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - dcmdb-data:/usr/local/mysql/data
      - ./docker/dcmdb/my.cnf:/etc/my.cnf
      - ./docker/dcmdb/sql/cakephptest.sql:/docker-entrypoint-initdb.d/01_cakephptest.sql
      - ./docker/dcmdb/sql/masterkanri.sql:/docker-entrypoint-initdb.d/02_masterkanri.sql

  spwebdb:
    image: mysql:5.5
    container_name: spweb-db
    environment:
      MYSQL_DATABASE: ${SPWEB_DB_NAME}
      MYSQL_USER: ${SPWEB_DB_USER}
      MYSQL_PASSWORD: ${SPWEB_DB_PASS}
      MYSQL_ROOT_PASSWORD: ${SPWEB_DB_PASS}
    volumes:
      - spwebdb-data:/var/lib/mysql
      - ./docker/spwebdb/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "${SPWEB_DB_PORT}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    container_name: phpmyadmin
    depends_on:
      - dcmdb
      - spwebdb
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_ARBITRARY: 1          # ローカル以外にも指定できるようになる
      PMA_HOSTS: dcmdb,spwebdb
      # PMA_USER: ${DB_USER}
      # PMA_PASSWORD: ${DB_PASS}
    restart: always

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "${MAIL_WEB_PORT}:8025"
      - "${MAIL_PORT}:1025"
    volumes:
      - mailhog-data:/tmp
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp

volumes:
  dcmdb-data:
  spwebdb-data:
  mailhog-data:
