services:
  dcmweb:
    build:
      context: ./docker/dcmweb
      dockerfile: Dockerfile
    container_name: dcm-web
    # db起動後にwebを起動
    depends_on:
      - dcmdb
    # ローカルのhtmlをコンテナの/var/www/htmlにマウント
    volumes:
      - ./html:/var/www/html
    # ポートを割り当て
    ports:
      - ${WEB_PORT}:80
      - ${WEB_SSL_PORT}:443
    command: >
      sh -c "
      cd /var/www/html &&
      composer install --no-interaction &&
      /usr/sbin/httpd -D FOREGROUND
      "
    tty: true

  dcmdb:
    # mysql:5.5イメージから構築
    image: mysql:5.5
    container_name: dcm-db
    volumes:
      - ./docker/dcmdb/my.cnf:/etc/mysql/conf.d/my.cnf
    # .envで環境変数を管理
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    # ポートを割り当て
    ports:
      - ${DB_PORT}:3306
